const { createProxyMiddleware } = require("http-proxy-middleware");
module.exports = function (app) {
  app.use(
    [
      "/student/login",
      "/student/valid",
      "/student/logout",
      "/student/register",
      "/student/pending",
      "/student/forgot-password",
      "/student/get-info",
      "/librarian/forgot-password",
      "/admin/forgot-password",
      "/librarian/scannerQrCode",
      "/book/single-add",
      "/book/batch-add",
      "/book/get-new",
      "/student/approve",
      "/book/get-genre",
      "/book/get-all-book-per-genre",
      "/book/get-available",
      "/book/add-shelf",
      "/book/get-info",
      "/book/get-borrowed",
      "/book/student-borrowed",
      "/book/student-shelf",
      "/book/get-reserved",
      "/book/get-lost",
      "/book/add-borrowed",
      "/book/add-reserved",
      "/book/add-lost",
      "/book",
      "/admin",
      "/librarian",
      "/uploads",
    ],
    createProxyMiddleware({
      target: "http://localhost:5000",
    })
  );
};
